// <auto-generated />
using System;
using GChan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GChan.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("GChan.Data.BoardData", b =>
                {
                    b.Property<int>("Site")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<long>("GreatestThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Site", "Code");

                    b.ToTable("BoardData");
                });

            modelBuilder.Entity("GChan.Data.ThreadData", b =>
                {
                    b.Property<int>("Site")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardCode")
                        .HasColumnType("TEXT");

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastScrape")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavedAssetIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("Site", "BoardCode", "Id");

                    b.ToTable("ThreadData");
                });
#pragma warning restore 612, 618
        }
    }
}
